// FLAMIN:LOCK FULLY_LOCKED
// Screen for ${feature} (${method} ${api_path}). Generated by flamin; do not edit.
import { useState } from "react";
import { Button, Text, TextInput, View } from "react-native";
import { ${Feature}Feature } from "../features/${Feature}Feature.ts";

const feature = new ${Feature}Feature();

export function ${Feature}Screen() {
  const [form, setForm] = useState<Record<string, string>>({});
  const [result, setResult] = useState("");
  return (
    <View>
${form_inputs_native}
      <Button
        title="${Feature}"
        onPress={async () => {
          try {
            setResult(JSON.stringify(await feature.${feature_camel}(form as never)));
          } catch (err) {
            setResult((err as Error).message);
          }
        }}
      />
      <Text>{result}</Text>
    </View>
  );
}
