// FLAMIN:LOCK FULLY_LOCKED
// Assembly for ${feature}: builds the internal transfer object from the storage model. Generated by flamin; do not edit.
export function toItem(row) {
  return { ${item_assign} };
}
