// FLAMIN:LOCK FULLY_LOCKED
// Standard response envelope: { code: 0, message: "ok", data }. Generated by flamin; do not edit.
export class FlaminError extends Error {
  constructor(code, message) {
    super(message);
    this.code = code;
  }
}

export function ok(data) {
  return { code: 0, message: "ok", data };
}

export function error(code, message) {
  return { code, message, data: {} };
}
