// FLAMIN:LOCK FULLY_LOCKED
// Storage model for ${Entity} (data layer). Generated by flamin from .flamin/design/${module}/model.toml; do not edit.
export function new${Entity}Model(${id_field}) {
  return {
${entity_defaults}
    ${id_field},
  };
}
