// FLAMIN:LOCK FULLY_LOCKED
// Base use case for ${feature} (read path). Generated by flamin; do not edit.
// Read path: interface -> application (this) -> data query -> assembly -> postProcessData -> view output.
import { FlaminError } from "../../../common/envelope.js";
import { toItem } from "../assembly/${Feature}Assembler.js";
import { ${Entity}Repository, ${entity_camel}Repository } from "../data/${Entity}Repository.js";

export class Base${Feature}Service {
  constructor(repository) {
    this.repository = repository ?? ${entity_camel}Repository;
  }

  ${feature_camel}(query, actor = "anonymous") {
    const data = query;
${required_checks}
    this.checkPermission(actor, query);
    const rows = this.repository.findBy((row) => ${filter_pred});
    const items = this.postProcessData(rows.map(toItem), query);
    return items.map((item) => ({ ${view_assign} }));
  }

  checkPermission() {
    throw new Error("checkPermission must be implemented");
  }

  postProcessData() {
    throw new Error("postProcessData must be implemented");
  }
}
