// FLAMIN:LOCK STRUCTURE_LOCKED
// Use case for ${feature}. Structure generated by flamin; write logic only inside the extension bodies.
import { Base${Feature}Service } from "./Base${Feature}Service.js";
// FLAMIN:EXTENSION imports
// FLAMIN:EXTENSION:END

export class ${Feature}Service extends Base${Feature}Service {
  checkPermission(actor, query) {
    // FLAMIN:EXTENSION checkPermission
    void actor; void query; // every actor passes through here; see .flamin/business/actors.md
    // FLAMIN:EXTENSION:END
  }

  postProcessData(items, query) {
    // FLAMIN:EXTENSION postProcessData
    void query;
    return items;
    // FLAMIN:EXTENSION:END
  }
}
