// FLAMIN:LOCK FULLY_LOCKED
// Data access for ${Entity}: in-memory store from the template. Generated by flamin; do not edit.
import { randomUUID } from "node:crypto";

export class ${Entity}Repository {
  rows = new Map();

  newId() {
    return randomUUID().replaceAll("-", "");
  }

  save(row) {
    this.rows.set(row.${id_field}, { ...row });
    return { ...row };
  }

  get(key) {
    const row = this.rows.get(key);
    return row ? { ...row } : undefined;
  }

  findBy(match) {
    return [...this.rows.values()].filter(match).map((r) => ({ ...r }));
  }

  clear() {
    this.rows.clear();
  }
}

export const ${entity_camel}Repository = new ${Entity}Repository();
