// FLAMIN:LOCK FULLY_LOCKED
// Public contract for ${feature} (${method} ${api_path}). Other modules call only this. Generated by flamin; do not edit.
// Write input fields and view output fields, as plain objects.
export const ${Feature}InputFields = Object.freeze([${input_names}]);
export const ${Feature}ViewFields = Object.freeze([${output_names}]);
