// FLAMIN:LOCK FULLY_LOCKED
// HTTP entry for ${feature}: ${method} ${api_path}. Generated by flamin; do not edit.
import { FlaminError, error, ok } from "../../../common/envelope.js";
import { ${Feature}Service } from "../application/${Feature}Service.js";

const service = new ${Feature}Service();

export function register(app) {
  app.${method_lower}("${api_path}", (req, res) => {
    const body = req.body ?? {};
    try {
      res.json(ok(service.${feature_camel}({ ${body_from_req} })));
    } catch (e) {
      if (e instanceof FlaminError) res.json(error(e.code, e.message));
      else throw e;
    }
  });
}
