// FLAMIN:LOCK FULLY_LOCKED
// Base use case for ${feature} (write path). Generated by flamin; do not edit.
// Write path: interface -> application (this) -> aggregate root check (validateAggregate) -> data.
import { FlaminError } from "../../../common/envelope.js";
import { toItem } from "../assembly/${Feature}Assembler.js";
import { new${Entity}Model } from "../data/${Entity}Model.js";
import { ${Entity}Repository, ${entity_camel}Repository } from "../data/${Entity}Repository.js";

export class Base${Feature}Service {
  constructor(repository) {
    this.repository = repository ?? ${entity_camel}Repository;
  }

  ${feature_camel}(data, actor = "anonymous") {
${required_checks}
    this.checkPermission(actor, data);
    const root = new${Entity}Model(this.repository.newId());
${stored_copy}
    this.validateAggregate(root, data);
    const item = toItem(this.repository.save(root));
    return { ${view_assign} };
  }

  checkPermission() {
    throw new Error("checkPermission must be implemented");
  }

  validateAggregate() {
    throw new Error("validateAggregate must be implemented");
  }
}
