// FLAMIN:LOCK FULLY_LOCKED
package app.modules.${module}.manager;

import app.modules.${module}.persist.${Entity}Model;

/** Assembly for ${feature}: builds the internal transfer object from the storage model. Generated by flamin; do not edit. */
public final class ${Feature}Assembler {
    /** Internal transfer object (never crosses the interface layer). */
    public record Item(${entity_params}) {}

    private ${Feature}Assembler() {}

    public static Item toItem(${Entity}Model row) {
        return new Item(${item_args});
    }
}
