// FLAMIN:LOCK FULLY_LOCKED
package app.common;

import java.util.Map;

/** Standard response envelope: {"code": 0, "message": "ok", "data": {...}}. Generated by flamin; do not edit. */
public record Envelope<T>(int code, String message, T data) {
    public static <T> Envelope<T> ok(T data) {
        return new Envelope<>(0, "ok", data);
    }

    public static Envelope<Map<String, Object>> error(int code, String message) {
        return new Envelope<>(code, message, Map.of());
    }
}
