// FLAMIN:LOCK FULLY_LOCKED
package app.common;

/** A business error with a non-zero code and a human-readable message. Generated by flamin; do not edit. */
public class FlaminException extends RuntimeException {
    private final int code;

    public FlaminException(int code, String message) {
        super(message);
        this.code = code;
    }

    public int code() {
        return code;
    }

    public static boolean isBlank(Object value) {
        return value == null || (value instanceof String s && s.isBlank());
    }
}
