// FLAMIN:LOCK FULLY_LOCKED
package app.modules.${module}.persist;

/** Storage model for ${Entity} (data layer). Generated by flamin from .flamin/design/${module}/model.toml; do not edit. */
public class ${Entity}Model {
${entity_fields_decl}

    public ${Entity}Model copy() {
        ${Entity}Model c = new ${Entity}Model();
${entity_copy}
        return c;
    }
}
