// FLAMIN:LOCK STRUCTURE_LOCKED
package app.modules.${module}.service;

import app.modules.${module}.manager.${Feature}Assembler;
import app.modules.${module}.persist.${Entity}Repository;
import java.util.List;
import org.springframework.stereotype.Service;
// FLAMIN:EXTENSION imports
// FLAMIN:EXTENSION:END

/** Use case for ${feature}. Structure generated by flamin; write logic only inside the extension bodies. */
@Service
public class ${Feature}Service extends Base${Feature}Service {
    public ${Feature}Service(${Entity}Repository repository) {
        super(repository);
    }

    @Override
    protected void checkPermission(String actor, Query query) {
        // FLAMIN:EXTENSION checkPermission
        // every actor passes through here; see .flamin/business/actors.md
        // FLAMIN:EXTENSION:END
    }

    @Override
    protected List<${Feature}Assembler.Item> postProcessData(List<${Feature}Assembler.Item> items, Query query) {
        // FLAMIN:EXTENSION postProcessData
        return items;
        // FLAMIN:EXTENSION:END
    }
}
