// FLAMIN:LOCK FULLY_LOCKED
package app.modules.${module}.contracts;

import java.util.List;

/** Public contract for ${feature} (${method} ${api_path}). Other modules call only this. Generated by flamin; do not edit. */
public interface ${Feature}Contract {
    /** Query input. */
    record Query(${input_params}) {}

    /** View output. */
    record View(${output_params}) {}

    List<View> ${feature_camel}(Query query, String actor);
}
