// FLAMIN:LOCK FULLY_LOCKED
package app.modules.${module}.service;

import app.common.FlaminException;
import app.modules.${module}.contracts.${Feature}Contract;
import app.modules.${module}.manager.${Feature}Assembler;
import app.modules.${module}.persist.${Entity}Repository;
import java.util.List;

/**
 * Base use case for ${feature} (read path). Generated by flamin; do not edit.
 * Read path: interface -> application (this) -> data query -> assembly -> postProcessData -> view output.
 */
public abstract class Base${Feature}Service implements ${Feature}Contract {
    protected final ${Entity}Repository repository;

    protected Base${Feature}Service(${Entity}Repository repository) {
        this.repository = repository;
    }

    @Override
    public List<View> ${feature_camel}(Query query, String actor) {
        Query data = query;
${required_checks}
        checkPermission(actor, query);
        List<${Feature}Assembler.Item> items = repository.findBy(row -> ${filter_pred}).stream()
                .map(${Feature}Assembler::toItem).toList();
        return postProcessData(items, query).stream().map(item -> new View(${view_args})).toList();
    }

    protected abstract void checkPermission(String actor, Query query);

    protected abstract List<${Feature}Assembler.Item> postProcessData(List<${Feature}Assembler.Item> items, Query query);
}
