// FLAMIN:LOCK FULLY_LOCKED
package app.modules.${module}.persist;

import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;
import java.util.function.Predicate;
import org.springframework.stereotype.Repository;

/** Data access for ${Entity}: in-memory store from the template. Generated by flamin; do not edit. */
@Repository
public class ${Entity}Repository {
    private final Map<String, ${Entity}Model> rows = new ConcurrentHashMap<>();

    public String newId() {
        return UUID.randomUUID().toString().replace("-", "");
    }

    public ${Entity}Model save(${Entity}Model row) {
        rows.put(row.${id_field}, row.copy());
        return row.copy();
    }

    public List<${Entity}Model> findBy(Predicate<${Entity}Model> match) {
        return rows.values().stream().filter(match).map(${Entity}Model::copy).toList();
    }

    public void clear() {
        rows.clear();
    }
}
