// FLAMIN:LOCK FULLY_LOCKED
package app.modules.${module}.entrance;

import app.common.Envelope;
import app.common.FlaminException;
import app.modules.${module}.contracts.${Feature}Contract;
import app.modules.${module}.service.${Feature}Service;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;

/** HTTP entry for ${feature}: ${method} ${api_path}. Generated by flamin; do not edit. */
@RestController
public class ${Feature}Controller {
    private final ${Feature}Service service;

    public ${Feature}Controller(${Feature}Service service) {
        this.service = service;
    }

    @RequestMapping(value = "${api_path}", method = RequestMethod.${method})
    public Envelope<?> handle(@RequestBody ${Feature}Contract.Input body) {
        try {
            return Envelope.ok(service.${feature_camel}(body, "anonymous"));
        } catch (FlaminException e) {
            return Envelope.error(e.code(), e.getMessage());
        }
    }
}
