// FLAMIN:LOCK FULLY_LOCKED
package app.modules.${module}.contracts;

/** Public contract for ${feature} (${method} ${api_path}). Other modules call only this. Generated by flamin; do not edit. */
public interface ${Feature}Contract {
    /** Write input. */
    record Input(${input_params}) {}

    /** View output. */
    record View(${output_params}) {}

    View ${feature_camel}(Input data, String actor);
}
