// FLAMIN:LOCK FULLY_LOCKED
package app.modules.${module}.service;

import app.common.FlaminException;
import app.modules.${module}.contracts.${Feature}Contract;
import app.modules.${module}.manager.${Feature}Assembler;
import app.modules.${module}.persist.${Entity}Model;
import app.modules.${module}.persist.${Entity}Repository;

/**
 * Base use case for ${feature} (write path). Generated by flamin; do not edit.
 * Write path: interface -> application (this) -> aggregate root check (validateAggregate) -> data.
 */
public abstract class Base${Feature}Service implements ${Feature}Contract {
    protected final ${Entity}Repository repository;

    protected Base${Feature}Service(${Entity}Repository repository) {
        this.repository = repository;
    }

    @Override
    public View ${feature_camel}(Input data, String actor) {
${required_checks}
        checkPermission(actor, data);
        ${Entity}Model root = new ${Entity}Model();
        root.${id_field} = repository.newId();
${stored_copy}
        validateAggregate(root, data);
        ${Feature}Assembler.Item item = ${Feature}Assembler.toItem(repository.save(root));
        return new View(${view_args});
    }

    protected abstract void checkPermission(String actor, Input data);

    protected abstract void validateAggregate(${Entity}Model root, Input data);
}
