// FLAMIN:LOCK STRUCTURE_LOCKED
package app.modules.${module}.service;

import app.modules.${module}.persist.${Entity}Model;
import app.modules.${module}.persist.${Entity}Repository;
import org.springframework.stereotype.Service;
// FLAMIN:EXTENSION imports
// FLAMIN:EXTENSION:END

/** Use case for ${feature}. Structure generated by flamin; write logic only inside the extension bodies. */
@Service
public class ${Feature}Service extends Base${Feature}Service {
    public ${Feature}Service(${Entity}Repository repository) {
        super(repository);
    }

    @Override
    protected void checkPermission(String actor, Input data) {
        // FLAMIN:EXTENSION checkPermission
        // every actor passes through here; see .flamin/business/actors.md
        // FLAMIN:EXTENSION:END
    }

    @Override
    protected void validateAggregate(${Entity}Model root, Input data) {
        // FLAMIN:EXTENSION validateAggregate
        // business rules for the ${Entity} aggregate, written once
        // FLAMIN:EXTENSION:END
    }
}
