# FLAMIN:LOCK FULLY_LOCKED
"""Assembly for ${feature}: builds the internal transfer object from the storage model. Generated by flamin; do not edit."""
from dataclasses import dataclass

from modules.${module}.repository.${entity_snake}_model import ${Entity}Model


@dataclass
class ${Feature}Item:
    """Internal transfer object (never crosses the interface layer)."""
${entity_fields_decl}


def to_item(row: ${Entity}Model) -> ${Feature}Item:
    return ${Feature}Item(${item_assign})
