# FLAMIN:LOCK FULLY_LOCKED
"""Standard response envelope: {"code": 0, "message": "ok", "data": {...}}. Generated by flamin; do not edit."""


class FlaminError(Exception):
    """A business error with a non-zero code and a human-readable message."""

    def __init__(self, code: int, message: str):
        super().__init__(message)
        self.code = code
        self.message = message


def ok(data=None) -> dict:
    return {"code": 0, "message": "ok", "data": data if data is not None else {}}


def error(code: int, message: str) -> dict:
    return {"code": code, "message": message, "data": {}}
