# FLAMIN:LOCK FULLY_LOCKED
"""Storage model for ${Entity} (data layer). Generated by flamin from .flamin/design/${module}/model.toml; do not edit."""
from dataclasses import dataclass


@dataclass
class ${Entity}Model:
${entity_fields_decl}
