# FLAMIN:LOCK FULLY_LOCKED
"""Base use case for ${feature} (read path). Generated by flamin; do not edit.

Read path: interface -> application (this) -> data query -> assembly -> postProcessData -> view output.
"""
from common.envelope import FlaminError
from modules.${module}.assemblers.${feature_snake}_assembler import ${Feature}Item, to_item
from modules.${module}.contracts.${feature_snake}_contract import ${Feature}Query, ${Feature}View
from modules.${module}.repository.${entity_snake}_repository import ${entity_snake}_repository

REQUIRED = [${required_names}]
FILTER = [${filter_names}]


class Base${Feature}Service:
    def __init__(self, repository=None):
        self.repository = repository or ${entity_snake}_repository

    def ${feature_snake}(self, query: ${Feature}Query, actor: str = "anonymous") -> list[${Feature}View]:
        for name in REQUIRED:
            if getattr(query, name) in (None, ""):
                raise FlaminError(400, f"{name} is required")
        self.check_permission(actor, query)
        rows = self.repository.find_by(**{name: getattr(query, name) for name in FILTER})
        items = self.post_process_data([to_item(r) for r in rows], query)
        return [${Feature}View(${view_assign}) for item in items]

    def check_permission(self, actor: str, query: ${Feature}Query) -> None:
        raise NotImplementedError

    def post_process_data(self, items: list[${Feature}Item], query: ${Feature}Query) -> list[${Feature}Item]:
        raise NotImplementedError
