# FLAMIN:LOCK STRUCTURE_LOCKED
"""Use case for ${feature}. Structure generated by flamin; write logic only inside the extension bodies."""
from modules.${module}.services.base_${feature_snake}_service import Base${Feature}Service

# FLAMIN:EXTENSION imports
# FLAMIN:EXTENSION:END


class ${Feature}Service(Base${Feature}Service):
    def check_permission(self, actor, query):
        # FLAMIN:EXTENSION checkPermission
        return None  # every actor passes through here; see .flamin/business/actors.md
        # FLAMIN:EXTENSION:END

    def post_process_data(self, items, query):
        # FLAMIN:EXTENSION postProcessData
        return items
        # FLAMIN:EXTENSION:END
