# FLAMIN:LOCK FULLY_LOCKED
"""HTTP entry for ${feature}: ${method} ${api_path}. Generated by flamin; do not edit."""
from dataclasses import asdict

from fastapi import APIRouter

from common.envelope import FlaminError, error, ok
from modules.${module}.contracts.${feature_snake}_contract import ${Feature}Query
from modules.${module}.services.${feature_snake}_service import ${Feature}Service

router = APIRouter()
service = ${Feature}Service()


@router.${method_lower}("${api_path}")
def ${feature_snake}_endpoint(${query_params}) -> dict:
    try:
        query = ${Feature}Query(**{k: v for k, v in {${query_assign}}.items() if v is not None})
        return ok([asdict(v) for v in service.${feature_snake}(query)])
    except FlaminError as exc:
        return error(exc.code, exc.message)
