# FLAMIN:LOCK FULLY_LOCKED
"""Data access for ${Entity}. Generated by flamin; do not edit.

This is the in-memory store from the template. A real database adapter is a new template (a template gap until then).
"""
import threading
import uuid
from dataclasses import replace

from modules.${module}.repository.${entity_snake}_model import ${Entity}Model


class ${Entity}Repository:
    def __init__(self):
        self._rows: dict[str, ${Entity}Model] = {}
        self._lock = threading.Lock()

    def new_id(self) -> str:
        return uuid.uuid4().hex

    def save(self, row: ${Entity}Model) -> ${Entity}Model:
        with self._lock:
            self._rows[row.${id_field}] = replace(row)
        return replace(row)

    def get(self, key: str) -> ${Entity}Model | None:
        with self._lock:
            row = self._rows.get(key)
            return replace(row) if row else None

    def find_by(self, **filters) -> list[${Entity}Model]:
        with self._lock:
            return [replace(r) for r in self._rows.values() if all(getattr(r, k) == v for k, v in filters.items())]

    def clear(self) -> None:
        with self._lock:
            self._rows.clear()


${entity_snake}_repository = ${Entity}Repository()
