# FLAMIN:LOCK FULLY_LOCKED
"""Public contract for ${feature} (${method} ${api_path}). Other modules call only this. Generated by flamin; do not edit."""
from dataclasses import dataclass
from typing import Protocol


@dataclass
class ${Feature}Input:
    """Write input."""
${input_fields_decl}


@dataclass
class ${Feature}View:
    """View output."""
${output_fields_decl}


class ${Feature}Contract(Protocol):
    def ${feature_snake}(self, data: ${Feature}Input, actor: str = "anonymous") -> ${Feature}View: ...
