# FLAMIN:LOCK FULLY_LOCKED
"""Base use case for ${feature} (write path). Generated by flamin; do not edit.

Write path: interface -> application (this) -> aggregate root check (validateAggregate) -> data.
"""
from common.envelope import FlaminError
from modules.${module}.assemblers.${feature_snake}_assembler import to_item
from modules.${module}.contracts.${feature_snake}_contract import ${Feature}Input, ${Feature}View
from modules.${module}.repository.${entity_snake}_model import ${Entity}Model
from modules.${module}.repository.${entity_snake}_repository import ${entity_snake}_repository

REQUIRED = [${required_names}]
STORED = [${stored_input_names}]


class Base${Feature}Service:
    def __init__(self, repository=None):
        self.repository = repository or ${entity_snake}_repository

    def ${feature_snake}(self, data: ${Feature}Input, actor: str = "anonymous") -> ${Feature}View:
        for name in REQUIRED:
            if getattr(data, name) in (None, ""):
                raise FlaminError(400, f"{name} is required")
        self.check_permission(actor, data)
        root = ${Entity}Model(${id_field}=self.repository.new_id())
        for name in STORED:
            setattr(root, name, getattr(data, name))
        self.validate_aggregate(root, data)
        item = to_item(self.repository.save(root))
        return ${Feature}View(${view_assign})

    def check_permission(self, actor: str, data: ${Feature}Input) -> None:
        raise NotImplementedError

    def validate_aggregate(self, root: ${Entity}Model, data: ${Feature}Input) -> None:
        raise NotImplementedError
