# FLAMIN:LOCK FULLY_LOCKED
"""HTTP entry for ${feature}: ${method} ${api_path}. Generated by flamin; do not edit."""
from dataclasses import asdict

from fastapi import APIRouter
from pydantic import BaseModel

from common.envelope import FlaminError, error, ok
from modules.${module}.contracts.${feature_snake}_contract import ${Feature}Input
from modules.${module}.services.${feature_snake}_service import ${Feature}Service

router = APIRouter()
service = ${Feature}Service()


class ${Feature}Body(BaseModel):
${body_fields}


@router.${method_lower}("${api_path}")
def ${feature_snake}_endpoint(body: ${Feature}Body) -> dict:
    try:
        data = ${Feature}Input(**{k: v for k, v in body.model_dump().items() if v is not None})
        return ok(asdict(service.${feature_snake}(data)))
    except FlaminError as exc:
        return error(exc.code, exc.message)
