// FLAMIN:LOCK FULLY_LOCKED
// Assembly for ${feature}: builds the internal transfer object from the backend's wire data. Generated by flamin; do not edit.
export interface ${Feature}Item {
${output_fields_decl}
}

export function toItem(raw: Record<string, unknown>): ${Feature}Item {
  return { ${wire_to_item} };
}
