// FLAMIN:LOCK FULLY_LOCKED
// Screen for ${feature} (${method} ${api_path}). Generated by flamin; do not edit.
import { useState } from "react";
import { ${Feature}Feature } from "../features/${Feature}Feature.ts";

const feature = new ${Feature}Feature();

export function ${Feature}Page() {
  const [form, setForm] = useState<Record<string, string>>({});
  const [result, setResult] = useState("");
  return (
    <form
      onSubmit={async (e) => {
        e.preventDefault();
        try {
          setResult(JSON.stringify(await feature.${feature_camel}(form as never)));
        } catch (err) {
          setResult((err as Error).message);
        }
      }}
    >
${form_inputs_web}
      <button type="submit">${Feature}</button>
      <output>{result}</output>
    </form>
  );
}
