// FLAMIN:LOCK FULLY_LOCKED
// Base use case for ${feature} on the client (read path). Generated by flamin; do not edit.
import { FlaminError } from "../../../common/envelope.ts";
import { toItem } from "../adapters/${Feature}Adapter.ts";
import type { ${Feature}Item } from "../adapters/${Feature}Adapter.ts";
import { ${feature_camel}Request } from "../api-client/${Feature}Client.ts";
import type { FetchFn } from "../api-client/${Feature}Client.ts";
import type { ${Feature}Contract, ${Feature}Query, ${Feature}View } from "../contracts/${Feature}Contract.ts";

export abstract class Base${Feature}Feature implements ${Feature}Contract {
  baseUrl: string;
  fetchFn: FetchFn;

  constructor(baseUrl: string = "", fetchFn?: FetchFn) {
    this.baseUrl = baseUrl;
    this.fetchFn = fetchFn ?? ((url, init) => fetch(url, init));
  }

  async ${feature_camel}(query: ${Feature}Query, actor: string = "anonymous"): Promise<${Feature}View[]> {
    const data = query;
${required_checks}
    this.checkPermission(actor, query);
    const env = await ${feature_camel}Request(query, this.baseUrl, this.fetchFn);
    if (env.code !== 0) throw new FlaminError(env.code, env.message);
    const items = this.postProcessData(env.data.map(toItem), query);
    return items.map((item) => ({ ${view_assign} }));
  }

  abstract checkPermission(actor: string, query: ${Feature}Query): void;

  abstract postProcessData(items: ${Feature}Item[], query: ${Feature}Query): ${Feature}Item[];
}
