// FLAMIN:LOCK STRUCTURE_LOCKED
// Use case for ${feature} on the client. Structure generated by flamin; write logic only inside the extension bodies.
import { Base${Feature}Feature } from "./Base${Feature}Feature.ts";
import type { ${Feature}Item } from "../adapters/${Feature}Adapter.ts";
import type { ${Feature}Query } from "../contracts/${Feature}Contract.ts";
// FLAMIN:EXTENSION imports
// FLAMIN:EXTENSION:END

export class ${Feature}Feature extends Base${Feature}Feature {
  checkPermission(actor: string, query: ${Feature}Query): void {
    // FLAMIN:EXTENSION checkPermission
    void actor; void query; // every actor passes through here; see .flamin/business/actors.md
    // FLAMIN:EXTENSION:END
  }

  postProcessData(items: ${Feature}Item[], query: ${Feature}Query): ${Feature}Item[] {
    // FLAMIN:EXTENSION postProcessData
    void query;
    return items;
    // FLAMIN:EXTENSION:END
  }
}
