// FLAMIN:LOCK FULLY_LOCKED
// Public contract for ${feature} (${method} ${api_path}). Other modules call only this. Generated by flamin; do not edit.
export interface ${Feature}Query {
${input_fields_decl}
}

export interface ${Feature}View {
${output_fields_decl}
}

export interface ${Feature}Contract {
  ${feature_camel}(query: ${Feature}Query, actor?: string): Promise<${Feature}View[]>;
}
