// FLAMIN:LOCK STRUCTURE_LOCKED
// Use case for ${feature} on the client. Structure generated by flamin; write logic only inside the extension bodies.
import { Base${Feature}Feature } from "./Base${Feature}Feature.ts";
import type { ${Feature}Input } from "../contracts/${Feature}Contract.ts";
// FLAMIN:EXTENSION imports
// FLAMIN:EXTENSION:END

export class ${Feature}Feature extends Base${Feature}Feature {
  checkPermission(actor: string, data: ${Feature}Input): void {
    // FLAMIN:EXTENSION checkPermission
    void actor; void data; // every actor passes through here; see .flamin/business/actors.md
    // FLAMIN:EXTENSION:END
  }

  validateAggregate(data: ${Feature}Input): void {
    // FLAMIN:EXTENSION validateAggregate
    void data; // client-side checks before the call; the backend's aggregate root stays the authority
    // FLAMIN:EXTENSION:END
  }
}
