// FLAMIN:LOCK FULLY_LOCKED
// Data layer for ${feature}: calls ${method} ${api_path} on the backend. Generated by flamin; do not edit.
import type { Envelope } from "../../../common/envelope.ts";

/** Request shape on the wire side (the data layer does not import contracts). */
export interface ${Feature}Request {
${input_fields_decl}
}

export type FetchFn = (url: string, init?: RequestInit) => Promise<Response>;

export async function ${feature_camel}Request(data: ${Feature}Request, baseUrl: string, fetchFn: FetchFn): Promise<Envelope<Record<string, unknown>>> {
  const res = await fetchFn(baseUrl + "${api_path}", {
    method: "${method}",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ ${wire_body} }),
  });
  return (await res.json()) as Envelope<Record<string, unknown>>;
}
