// FLAMIN:LOCK FULLY_LOCKED
// Base use case for ${feature} on the client (write path). Generated by flamin; do not edit.
import { FlaminError } from "../../../common/envelope.ts";
import { toItem } from "../adapters/${Feature}Adapter.ts";
import type { ${Feature}Item } from "../adapters/${Feature}Adapter.ts";
import { ${feature_camel}Request } from "../api-client/${Feature}Client.ts";
import type { FetchFn } from "../api-client/${Feature}Client.ts";
import type { ${Feature}Contract, ${Feature}Input, ${Feature}View } from "../contracts/${Feature}Contract.ts";

export abstract class Base${Feature}Feature implements ${Feature}Contract {
  baseUrl: string;
  fetchFn: FetchFn;

  constructor(baseUrl: string = "", fetchFn?: FetchFn) {
    this.baseUrl = baseUrl;
    this.fetchFn = fetchFn ?? ((url, init) => fetch(url, init));
  }

  async ${feature_camel}(data: ${Feature}Input, actor: string = "anonymous"): Promise<${Feature}View> {
${required_checks}
    this.checkPermission(actor, data);
    this.validateAggregate(data);
    const env = await ${feature_camel}Request(data, this.baseUrl, this.fetchFn);
    if (env.code !== 0) throw new FlaminError(env.code, env.message);
    const item: ${Feature}Item = toItem(env.data);
    return { ${view_assign} };
  }

  abstract checkPermission(actor: string, data: ${Feature}Input): void;

  abstract validateAggregate(data: ${Feature}Input): void;
}
