// FLAMIN:LOCK FULLY_LOCKED
// Assembly for ${feature}: builds the internal transfer object from the storage model. Generated by flamin; do not edit.
import type { ${Entity}Model } from "../data/${Entity}Model.ts";

export interface ${Feature}Item {
${entity_fields_decl}
}

export function toItem(row: ${Entity}Model): ${Feature}Item {
  return { ${item_assign} };
}
