// FLAMIN:LOCK FULLY_LOCKED
// Standard response envelope: { code: 0, message: "ok", data }. Generated by flamin; do not edit.
export interface Envelope<T> {
  code: number;
  message: string;
  data: T;
}

export class FlaminError extends Error {
  code: number;
  constructor(code: number, message: string) {
    super(message);
    this.code = code;
  }
}

export function ok<T>(data: T): Envelope<T> {
  return { code: 0, message: "ok", data };
}

export function error(code: number, message: string): Envelope<Record<string, never>> {
  return { code, message, data: {} };
}
