// FLAMIN:LOCK FULLY_LOCKED
// Storage model for ${Entity} (data layer). Generated by flamin from .flamin/design/${module}/model.toml; do not edit.
export interface ${Entity}Model {
${entity_fields_decl}
}

export function new${Entity}Model(${id_field}: string): ${Entity}Model {
  return {
${entity_defaults}
    ${id_field},
  };
}
