// FLAMIN:LOCK FULLY_LOCKED
// Base use case for ${feature} (read path). Generated by flamin; do not edit.
// Read path: interface -> application (this) -> data query -> assembly -> postProcessData -> view output.
import { FlaminError } from "../../../common/envelope.ts";
import { toItem } from "../assembly/${Feature}Assembler.ts";
import type { ${Feature}Item } from "../assembly/${Feature}Assembler.ts";
import type { ${Feature}Contract, ${Feature}Query, ${Feature}View } from "../contracts/${Feature}Contract.ts";
import { ${Entity}Repository, ${entity_camel}Repository } from "../data/${Entity}Repository.ts";

export abstract class Base${Feature}Service implements ${Feature}Contract {
  repository: ${Entity}Repository;

  constructor(repository?: ${Entity}Repository) {
    this.repository = repository ?? ${entity_camel}Repository;
  }

  ${feature_camel}(query: ${Feature}Query, actor: string = "anonymous"): ${Feature}View[] {
    const data = query;
${required_checks}
    this.checkPermission(actor, query);
    const rows = this.repository.findBy((row) => ${filter_pred});
    const items = this.postProcessData(rows.map(toItem), query);
    return items.map((item) => ({ ${view_assign} }));
  }

  abstract checkPermission(actor: string, query: ${Feature}Query): void;

  abstract postProcessData(items: ${Feature}Item[], query: ${Feature}Query): ${Feature}Item[];
}
