// FLAMIN:LOCK FULLY_LOCKED
// Data access for ${Entity}: in-memory store from the template. Generated by flamin; do not edit.
import { randomUUID } from "node:crypto";
import type { ${Entity}Model } from "./${Entity}Model.ts";

export class ${Entity}Repository {
  private rows = new Map<string, ${Entity}Model>();

  newId(): string {
    return randomUUID().replaceAll("-", "");
  }

  save(row: ${Entity}Model): ${Entity}Model {
    this.rows.set(row.${id_field}, { ...row });
    return { ...row };
  }

  get(key: string): ${Entity}Model | undefined {
    const row = this.rows.get(key);
    return row ? { ...row } : undefined;
  }

  findBy(match: (row: ${Entity}Model) => boolean): ${Entity}Model[] {
    return [...this.rows.values()].filter(match).map((r) => ({ ...r }));
  }

  clear(): void {
    this.rows.clear();
  }
}

export const ${entity_camel}Repository = new ${Entity}Repository();
