// FLAMIN:LOCK FULLY_LOCKED
// Public contract for ${feature} (${method} ${api_path}). Other modules call only this. Generated by flamin; do not edit.
export interface ${Feature}Input {
${input_fields_decl}
}

export interface ${Feature}View {
${output_fields_decl}
}

export interface ${Feature}Contract {
  ${feature_camel}(data: ${Feature}Input, actor?: string): ${Feature}View;
}
