// FLAMIN:LOCK STRUCTURE_LOCKED
// Use case for ${feature}. Structure generated by flamin; write logic only inside the extension bodies.
import { Base${Feature}Service } from "./Base${Feature}Service.ts";
import type { ${Feature}Input } from "../contracts/${Feature}Contract.ts";
import type { ${Entity}Model } from "../data/${Entity}Model.ts";
// FLAMIN:EXTENSION imports
// FLAMIN:EXTENSION:END

export class ${Feature}Service extends Base${Feature}Service {
  checkPermission(actor: string, data: ${Feature}Input): void {
    // FLAMIN:EXTENSION checkPermission
    void actor; void data; // every actor passes through here; see .flamin/business/actors.md
    // FLAMIN:EXTENSION:END
  }

  validateAggregate(root: ${Entity}Model, data: ${Feature}Input): void {
    // FLAMIN:EXTENSION validateAggregate
    void root; void data; // business rules for the ${Entity} aggregate, written once
    // FLAMIN:EXTENSION:END
  }
}
