// FLAMIN:LOCK FULLY_LOCKED
// Base use case for ${feature} (write path). Generated by flamin; do not edit.
// Write path: interface -> application (this) -> aggregate root check (validateAggregate) -> data.
import { FlaminError } from "../../../common/envelope.ts";
import { toItem } from "../assembly/${Feature}Assembler.ts";
import type { ${Feature}Contract, ${Feature}Input, ${Feature}View } from "../contracts/${Feature}Contract.ts";
import { new${Entity}Model } from "../data/${Entity}Model.ts";
import type { ${Entity}Model } from "../data/${Entity}Model.ts";
import { ${Entity}Repository, ${entity_camel}Repository } from "../data/${Entity}Repository.ts";

export abstract class Base${Feature}Service implements ${Feature}Contract {
  repository: ${Entity}Repository;

  constructor(repository?: ${Entity}Repository) {
    this.repository = repository ?? ${entity_camel}Repository;
  }

  ${feature_camel}(data: ${Feature}Input, actor: string = "anonymous"): ${Feature}View {
${required_checks}
    this.checkPermission(actor, data);
    const root = new${Entity}Model(this.repository.newId());
${stored_copy}
    this.validateAggregate(root, data);
    const item = toItem(this.repository.save(root));
    return { ${view_assign} };
  }

  abstract checkPermission(actor: string, data: ${Feature}Input): void;

  abstract validateAggregate(root: ${Entity}Model, data: ${Feature}Input): void;
}
