# FLAMIN:LOCK FULLY_LOCKED
"""Base for ${feature}. Generated by flamin; do not edit. (minimal profile: no layers, lock levels and phases only)"""

REQUIRED = [${required_names}]


class Base${Feature}:
    def run(self, actor: str = "anonymous", **inputs) -> list:
        for name in REQUIRED:
            if inputs.get(name) in (None, ""):
                raise ValueError(f"{name} is required")
        self.check_permission(actor, inputs)
        return self.post_process_data([], inputs)

    def check_permission(self, actor, inputs):
        raise NotImplementedError

    def post_process_data(self, items, inputs):
        raise NotImplementedError
