# FLAMIN:LOCK STRUCTURE_LOCKED
"""${feature}. Structure generated by flamin; write logic only inside the extension bodies."""
from .${feature_snake}_base import Base${Feature}

# FLAMIN:EXTENSION imports
# FLAMIN:EXTENSION:END


class ${Feature}(Base${Feature}):
    def check_permission(self, actor, inputs):
        # FLAMIN:EXTENSION checkPermission
        return None
        # FLAMIN:EXTENSION:END

    def post_process_data(self, items, inputs):
        # FLAMIN:EXTENSION postProcessData
        return items
        # FLAMIN:EXTENSION:END
