# FLAMIN:LOCK FULLY_LOCKED
"""Base for ${feature}. Generated by flamin; do not edit. (minimal profile: no layers, lock levels and phases only)"""

REQUIRED = [${required_names}]


class Base${Feature}:
    def run(self, actor: str = "anonymous", **inputs) -> dict:
        for name in REQUIRED:
            if inputs.get(name) in (None, ""):
                raise ValueError(f"{name} is required")
        self.check_permission(actor, inputs)
        self.validate_aggregate(inputs)
        return inputs

    def check_permission(self, actor, inputs):
        raise NotImplementedError

    def validate_aggregate(self, inputs):
        raise NotImplementedError
